### ISSUE TITLE
Unable to set minRows to 1

### ISSUE THREAD

**Issue by mgzurakowski** [chrum/ngx-autosize#34]
Looks like there's no possibility to set start "height" to 1 row. When I set [minRows] to 1 it still displays 2 rows.

**Comment by chrum** [comment]
hey @mgzurakowski 

try version at **next** channel:

`npm install ngx-autosize@next`

**Comment by mrkorsar** [comment]
It's still reproducing. You could see this on this page https://chrum.it/pages/ngx-autosize/ All you need it is to open this page by FireFox browser and enter value "1" into "Min rows" field

**Comment by chrum** [comment]
@mrkorsar i didnt update the demo page... please reload it and check now

**Comment by mrkorsar** [comment]
@chrum thank you for answer! As you can see now, there are different height in different browsers. In Chrome textarea has 38px of height for 1 row and in FireFox this value is 55px. It looks like a bug

**Comment by chrum** [comment]
true, but thats like a different issue, please one new one

**Comment by chrum** [comment]
ok, i can do it myself :) #43

**Comment by jaco-fq** [comment]
Fixed it here! https://github.com/chrum/ngx-autosize/pull/44

**Comment by jaco-fq** [comment]
The demo page works fine for me, but when I use ngx-autosize in an Ionic app, it breaks. #44 fixes the problem for me.

**Comment by mayankkataria** [comment]
I tried that ```@next``` command but I'm still facing this issue with ```<ion-textarea>``` component in ionic.

**Comment by bardonadam** [comment]
I also still have this issue, even with version 1.8.5.
